"""Produce a solution-free copy of an exam notebook, with blank writing space.

Exam notebooks (e.g. hw/sample-midterm.ipynb) interleave each problem's markdown
cell with a markdown "Solution:" cell. Solution cells are tagged with a cell tag
(default: "solution") -- see `solution()` in the notebook's build script, or add
the tag by hand in Jupyter (View -> Cell Toolbar -> Tags).

This script finds every cell carrying that tag and replaces it (same position)
with a blank markdown cell: a stack of HTML `<br/>` line breaks sized to the
problem's point value (parsed from "(N marks)" in the *preceding* cell), followed
by `<div style="page-break-after: always"></div>` so the next problem starts on a
fresh page when printed/exported to PDF. The original notebook is never modified;
output goes to a new file.

    python3 scripts/strip_solutions.py hw/sample-midterm.ipynb
        -> writes hw/sample-midterm-blank.ipynb

    python3 scripts/strip_solutions.py hw/sample-midterm.ipynb -o hw/exam-handout.ipynb

    python3 scripts/strip_solutions.py hw/sample-midterm.ipynb --lines-per-mark 1 --no-page-break
"""
import argparse
import json
import os
import re

MARKS_RE = re.compile(r"(\d+)\s*marks?\)", re.IGNORECASE)

PAGE_BREAK_DIV = '<div style="page-break-after: always" ></div>'


def load_notebook(path):
    with open(path) as f:
        return json.load(f)


def cell_source_text(cell):
    src = cell.get("source", [])
    return "".join(src) if isinstance(src, list) else src


def has_tag(cell, tag):
    return tag in cell.get("metadata", {}).get("tags", [])


def marks_for_problem(preceding_cell):
    """Best-guess point value of the problem a solution cell answers, taken as
    the largest "(N marks)" figure in the immediately preceding cell (the
    problem's own mark total is usually the largest single number mentioned --
    sub-parts are smaller fractions of it)."""
    if preceding_cell is None:
        return None
    found = MARKS_RE.findall(cell_source_text(preceding_cell))
    return max((int(n) for n in found), default=None)


def make_blank_cell(n_lines, page_break, cell_id=None):
    lines = ["<br/>"] * n_lines
    body = "\n".join(lines)
    parts = [
        "<!-- blank space generated by scripts/strip_solutions.py "
        "(original solution cell removed) -->",
        body,
    ]
    if page_break:
        parts.append("")
        parts.append(PAGE_BREAK_DIV)
    text = "\n".join(parts)
    src_lines = text.split("\n")
    source = [l + "\n" for l in src_lines[:-1]] + [src_lines[-1]]
    cell = {"cell_type": "markdown", "metadata": {}, "source": source}
    if cell_id is not None:
        cell["id"] = cell_id
    return cell


def strip_solutions(nb, tag, lines_per_mark, default_lines, min_lines, max_lines, page_break):
    cells = nb["cells"]
    new_cells = []
    n_replaced = 0
    for i, cell in enumerate(cells):
        if cell.get("cell_type") == "markdown" and has_tag(cell, tag):
            marks = marks_for_problem(cells[i - 1] if i > 0 else None)
            n_lines = default_lines if marks is None else marks * lines_per_mark
            n_lines = max(min_lines, min(max_lines, n_lines))
            # keep the original cell's id (if any) so the blank cell occupies
            # the same logical slot rather than minting a fresh identity
            new_cells.append(make_blank_cell(n_lines, page_break, cell_id=cell.get("id")))
            n_replaced += 1
        else:
            new_cells.append(cell)
    nb["cells"] = new_cells
    return nb, n_replaced


def default_output_path(input_path):
    root, ext = os.path.splitext(input_path)
    return f"{root}-blank{ext}"


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("notebook", help="path to the source .ipynb (with tagged solution cells)")
    ap.add_argument("-o", "--output", help="output .ipynb path (default: NAME-blank.ipynb)")
    ap.add_argument("--tag", default="solution", help="cell tag identifying a solution cell (default: solution)")
    ap.add_argument("--lines-per-mark", type=int, default=2,
                     help="<br/> lines of blank space per point value (default: 2)")
    ap.add_argument("--default-lines", type=int, default=10,
                     help="blank lines to use when a problem's mark value can't be parsed (default: 10)")
    ap.add_argument("--min-lines", type=int, default=4, help="floor on blank lines per problem (default: 4)")
    ap.add_argument("--max-lines", type=int, default=40, help="cap on blank lines per problem (default: 40)")
    ap.add_argument("--no-page-break", action="store_true",
                     help="don't insert a page-break div after each blank space")
    args = ap.parse_args()

    nb = load_notebook(args.notebook)
    nb, n_replaced = strip_solutions(
        nb,
        tag=args.tag,
        lines_per_mark=args.lines_per_mark,
        default_lines=args.default_lines,
        min_lines=args.min_lines,
        max_lines=args.max_lines,
        page_break=not args.no_page_break,
    )
    if n_replaced == 0:
        raise SystemExit(
            f"no cells tagged {args.tag!r} found in {args.notebook} -- "
            f"nothing to strip (check the tag name with --tag)"
        )

    out_path = args.output or default_output_path(args.notebook)
    with open(out_path, "w") as f:
        json.dump(nb, f, indent=1)
    print(f"wrote {out_path} ({n_replaced} solution cell(s) replaced with blank space)")


if __name__ == "__main__":
    main()
